In [2]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [6]:
a = np.random.random((3,3,3))
a

array([[[0.87372772, 0.23547073, 0.25847972],
        [0.73256719, 0.25067467, 0.89116209],
        [0.24830979, 0.32485709, 0.15610859]],

       [[0.99838082, 0.05086673, 0.65302987],
        [0.63205625, 0.0429773 , 0.09766418],
        [0.97035339, 0.4061185 , 0.5998893 ]],

       [[0.21792814, 0.92174943, 0.14147805],
        [0.54105311, 0.46009059, 0.53433525],
        [0.98173566, 0.92101267, 0.57490706]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [22]:
b = np.eye(5,5)
for i in range(1,5):
    b[i,i-1] = i
print(b.astype(int))    

[[1 0 0 0 0]
 [1 1 0 0 0]
 [0 2 1 0 0]
 [0 0 3 1 0]
 [0 0 0 4 1]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [50]:
cb = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i+j)%2 == 0:
            cb[i,j] = 0
        else:
            cb[i,j] = 1
print('Checkerboard Pattern :')
print(cb.astype(int))

Checkerboard Pattern :
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [37]:
n = np.random.random((5,5))
print('Before Normalization :','\n\n',n)
n = (n  - n.min())/(n.max() - n.min())
print('\nAfter Normalization :','\n\n',n)

Before Normalization : 

 [[0.15138273 0.29887548 0.86322852 0.2534954  0.04555221]
 [0.50383026 0.64823561 0.69461502 0.02018284 0.21493455]
 [0.83528805 0.70986026 0.32337991 0.93462784 0.85223534]
 [0.50229449 0.28911306 0.56352673 0.21701774 0.38372911]
 [0.20477988 0.42036501 0.44296695 0.93257282 0.25661412]]

After Normalization : 

 [[0.14347488 0.30476697 0.92192059 0.25514116 0.02774291]
 [0.52889722 0.68681307 0.73753171 0.         0.21297258]
 [0.89136603 0.75420329 0.33156403 1.         0.9098989 ]
 [0.52721776 0.29409119 0.59417886 0.21525067 0.39755947]
 [0.20186784 0.437623   0.46233957 0.99775272 0.25855166]]


# 5.  How to find common values between two arrays?

In [48]:
a = np.array([1,2,6,3,87,343,67,90])
b = np.array([45,67,89,90,3,234,56,456,789,987])
print('The common values between two arrays are: ')
print(','.join(map(str,np.intersect1d(a,b))))

The common values between two arrays are: 
3,67,90


# 6.How to get the dates of yesterday, today and tomorrow?

In [67]:
today = np.datetime64('today','D')  
yesterday = np.datetime64('today','D')  - np.timedelta64(1,'D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')

print('Yesterday:',yesterday)
print('Today    :',today)
print('Tomorrow :', tomorrow)

Yesterday: 2020-07-24
Today    : 2020-07-25
Tomorrow : 2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [90]:
a = np.random.random((5,5))
b = np.random.random((5,5))
print(a,'\n\n',b,'\n')
if np.allclose(a,b):
    print('Two arrays are equal')
else:
    print('Two arrays are not equal')

[[0.86929498 0.73907196 0.29189038 0.98926785 0.35363963]
 [0.69649711 0.47359391 0.3320075  0.16475331 0.23142789]
 [0.27055947 0.05924162 0.2583415  0.75799384 0.2250571 ]
 [0.82215058 0.44473371 0.75167614 0.91579064 0.84694771]
 [0.04389085 0.45579866 0.43111675 0.38522567 0.39212368]] 

 [[0.69746449 0.84263556 0.13454368 0.18780181 0.73872045]
 [0.54944139 0.37244495 0.63300533 0.79202863 0.95361337]
 [0.44114244 0.37328995 0.24102611 0.65428696 0.15082081]
 [0.90135378 0.61924522 0.76710871 0.67900504 0.06206064]
 [0.23752095 0.87373746 0.8194951  0.75506375 0.98001251]] 

Two arrays are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [107]:
x = np.random.random(10)
x.sort()
print(x[-1],'\n')
x[-1] = 0
print(int(x[-1]))

0.9142074514663602 

0


# 9. How to print all the values of an array?

In [110]:
a = np.array([1,2,3,4,5,6,7,9,10])
print(a)

[ 1  2  3  4  5  6  7  9 10]


# 10.Subtract the mean of each row of a matrix

In [123]:
a = np.random.random((5,5))
print(a,'\n')
b = a - a.mean(axis = 1)
print('After Subtracting the mean of each row of a matrix:\n')
print(b)

[[0.38244657 0.28403914 0.14819662 0.77733354 0.56338476]
 [0.76785314 0.38952481 0.61858015 0.99907479 0.60938616]
 [0.63357576 0.12225656 0.25318273 0.2407247  0.51618062]
 [0.40551736 0.15470533 0.48486558 0.5252095  0.52300822]
 [0.29017322 0.47183137 0.30351499 0.73794307 0.97245449]] 

After Subtracting the mean of each row of a matrix:

[[-0.04863356 -0.39284466 -0.20498746  0.35867235  0.00820133]
 [ 0.33677301 -0.287359    0.26539607  0.5804136   0.05420273]
 [ 0.20249563 -0.55462725 -0.10000134 -0.1779365  -0.0390028 ]
 [-0.02556277 -0.52217847  0.1316815   0.1065483  -0.03217521]
 [-0.14090691 -0.20505244 -0.04966909  0.31928188  0.41727106]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [132]:
a= np.array([1,3,5,7,2,4,17,9,347,5,12,56,234])
b = np.array([0,5,6,9,0,5,12])
b = list(set(b))
print(a)  
for i in range(len(a)):
    if i in b:
        a[i]+=1
print('After adding 1 to each element indexed by a second vector: ')
print(a)        

[  1   3   5   7   2   4  17   9 347   5  12  56 234]
After adding 1 to each element indexed by a second vector: 
[  2   3   5   7   2   5  18   9 347   6  12  56 235]


# 12.How to get the diagonal of a dot product?

In [161]:
a = np.array([[1,3,5],[12,14,13],[2,1,6]])
b = np.array([[6,4,2],[15,13,16],[21,11,36]])
print(a,'\n')
print(b,'\n')
diagonal = a.dot(b)
print(diagonal,'\n')
print(np.diag(diagonal))

[[ 1  3  5]
 [12 14 13]
 [ 2  1  6]] 

[[ 6  4  2]
 [15 13 16]
 [21 11 36]] 

[[156  98 230]
 [555 373 716]
 [153  87 236]] 

[156 373 236]


# 13.How to find the most frequent value in an array?

In [168]:
from scipy.stats import *
a= np.array([1,3,5,7,2,4,7,9,7,5,12,56,234])
print('The most frequent value in the array is:',stats.mode(a)[0][0])

The most frequent value in the array is: 7


# 14.How to get the n largest values of an array

In [174]:
n = 3
a = np.array([1,3,5,7,2,4,7,9,7,5,12,56,24])
a.sort()
print(a)
print('The n largest value is:',a[-n])

[ 1  2  3  4  5  5  7  7  7  9 12 24 56]
The n largest value is: 12


# 15.How to create a record array from a regular array?

In [183]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])

record_array = np.core.records.fromarrays([a1,a2,a3],names = 'a,b,c')
print('Record Array is:')
print(record_array[0])
print(record_array[1])
print(record_array[2])
print(record_array[3])

Record Array is:
(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
(4, 'Orange', 40.)
